language: ruby
rvm:
- 2.1
before_install:
- travis_retry gem install jekyll
- travis_retry gem install rdiscount
script: jekyll build

# branch whitelist
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
